"""
review_bboxes.py
================
Interactive review & edit of 2D bounding boxes generated by
`collect_gt_dataset.py` (the blueprint-style dataset under
<project_root>/datasets/<session>).

Project + IO
------------
- Project root is discovered via `resolve_project_root(...)`.
- By default, the dataset root is <project_root>/datasets (override with --dataset_root).
- This tool scans:   datasets/<session>/annotations/*.json
- It displays:       datasets/<session>/(images|annotated)/<image_filename>
- On save it **atomically** patches only these fields for edited objects:
    objects[i].2D_center  (normalized [cx, cy])
    objects[i].width      (normalized)
    objects[i].height     (normalized)
    objects[i].bbox_source = "manual"
  All other metadata (poses, intrinsics, reproj paths, etc.) remain untouched.

Resume / Progress
-----------------
- Progress is tracked so you can quit and resume later.
- A lightweight state file is written to:
    datasets/<session>/annotations/.review/review_progress.json
  When the script restarts for the same session, it jumps back to the last
  reviewed frame and selected object. The UI shows a progress bar
  "<reviewed>/<total> reviewed".

What you can do
---------------
- Click inside a box to select it.
- Drag inside a selected box to **move** it.
- Drag from box edges/corners (handles) to **resize** it.
- Press **E** to draw a brand-new box for the selected object (click-drag, release to set).
- Press **ESC** while drawing to cancel the pending edit.
- **ENTER / Y / S** saves current frame JSON (apply edits) and advances.
- **N** advances without saving.
- **U** undoes the selected object (reverts to the original values from file).
- **R** resets **all** objects in the current frame to their original values.
- Arrow/WASD:
    ↑/W and ↓/S   select previous/next object in frame
    ←/A and →/D   previous/next frame (navigation only; no save)

View / Appearance
-----------------
- Left: image with current and selected boxes (selected = yellow with handles).
- Right: compact status panel (project root, session, frame counter, selected
  class, normalized bbox, source, mode) and keymap.
- The panel height matches the image height (no bottom black band). Wide text
  lines auto-fit the panel.

Usage
-----
  python -m src.review_bboxes --session run01
  python -m src.review_bboxes --session run01 --dataset_root /abs/path/to/datasets
  python -m src.review_bboxes --session run01 --filter-class connection_plate
  python -m src.review_bboxes --session run01 --use-annotated

Notes
-----
- Only normalized bbox fields (+bbox_source) are modified.
- JSON files are written via a temp file and then moved (atomic on POSIX).
- If an annotation JSON has zero objects (or fails to load), it is skipped.
- `--use-annotated` shows the annotated overlay PNGs as background; otherwise
  the tag-covered raw images from `images/` are used.

Dependencies
------------
OpenCV, numpy, PyYAML, and repo utils:
  utils.project_config: resolve_project_root, ensure_project_dirs
  utils.logger: init_project_logger
"""


from __future__ import annotations
import argparse, json, sys, logging, shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple, Dict, Set

import cv2
import numpy as np

from utils.project_config import resolve_project_root, ensure_project_dirs
from utils.logger import init_project_logger

log: logging.Logger

ROW_H = 22
FONT = cv2.FONT_HERSHEY_SIMPLEX
FS = 0.5
THICK = 1
COLOR = (0, 255, 255)
COLOR_BAR = (0, 255, 255)
HANDLE_SIZE = 12  # larger grip squares
HANDLE_HIT = 14  # easier to grab
PROGRESS_FILE = ".bbox_review_state.json"

# ---------------------------- Data structures ----------------------------

@dataclass
class ObjAnno:
    index: int
    class_id: int
    class_name: str
    cx: float  # normalized [0..1]
    cy: float
    w: float
    h: float
    bbox_source: Optional[str] = None
    # originals to support undo/reset:
    _orig_cx: float = field(default=None)
    _orig_cy: float = field(default=None)
    _orig_w: float = field(default=None)
    _orig_h: float = field(default=None)
    _orig_src: Optional[str] = field(default=None)

    def remember_orig(self):
        self._orig_cx, self._orig_cy = self.cx, self.cy
        self._orig_w, self._orig_h = self.w, self.h
        self._orig_src = self.bbox_source

    def undo(self):
        if self._orig_cx is not None:
            self.cx, self.cy, self.w, self.h = self._orig_cx, self._orig_cy, self._orig_w, self._orig_h
            self.bbox_source = self._orig_src


@dataclass
class FrameRec:
    idx_name: str  # e.g. Run_YYYYMMDD-HHMMSS_frame_000123
    json_path: Path
    image_path: Path
    objects: List[ObjAnno]


# ---------------------------- Helpers ----------------------------

def _atomic_write_json(path: Path, obj: dict):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2))
    shutil.move(str(tmp), str(path))


def _list_frames(session_dir: Path, use_annotated: bool, filter_cls: Optional[str]) -> List[FrameRec]:
    ann_dir = session_dir / "annotations"
    img_dir = session_dir / ("annotated" if use_annotated else "images")
    if not ann_dir.exists():
        raise SystemExit(f"[!] annotations dir not found: {ann_dir}")
    jsons = sorted(ann_dir.glob("*.json"))
    out: List[FrameRec] = []
    for jp in jsons:
        try:
            rec = json.loads(jp.read_text())
            img_name = rec.get("image_filename")
            if not img_name:
                continue
            ip = img_dir / img_name  # annotated/raw share same filename
            objs = []
            for i, o in enumerate(rec.get("objects", [])):
                cls = str(o.get("class_name", ""))
                if filter_cls and filter_cls.lower() not in cls.lower():
                    continue
                cx, cy = o.get("2D_center", [0.5, 0.5])
                w, h = float(o.get("width", 0.0)), float(o.get("height", 0.0))
                oa = ObjAnno(
                    index=i,
                    class_id=int(o.get("class_id", -1)),
                    class_name=cls,
                    cx=float(cx), cy=float(cy), w=w, h=h,
                    bbox_source=o.get("bbox_source"),
                )
                oa.remember_orig()
                objs.append(oa)
            if filter_cls and not objs:
                continue
            idx_name = jp.stem
            out.append(FrameRec(idx_name=idx_name, json_path=jp, image_path=ip, objects=objs))
        except Exception as e:
            log.warning("[skip] bad annotation %s: %s", jp, e)
    return out


def _norm_to_xywh_px(cx: float, cy: float, w: float, h: float, W: int, H: int) -> Tuple[int, int, int, int]:
    x = (cx - 0.5 * w) * W
    y = (cy - 0.5 * h) * H
    return int(round(x)), int(round(y)), int(round(w * W)), int(round(h * H))


def _xywh_px_to_norm(x: float, y: float, w: float, h: float, W: int, H: int) -> Tuple[float, float, float, float]:
    cx = (x + 0.5 * w) / float(W)
    cy = (y + 0.5 * h) / float(H)
    ww = w / float(W)
    hh = h / float(H)
    return cx, cy, ww, hh


def _clamp_xywh(x: float, y: float, w: float, h: float, W: int, H: int) -> Tuple[float, float, float, float]:
    x = max(0.0, min(W - 1.0, x))
    y = max(0.0, min(H - 1.0, y))
    w = max(0.0, min(W - 1.0 - x, w))
    h = max(0.0, min(H - 1.0 - y, h))
    return x, y, w, h


def _text_size(s: str, font=FONT, fs=FS, thick=THICK):
    (w, h), _ = cv2.getTextSize(s, font, fs, thick)
    return w, h


def _kv(img, y, key, val, x_key=10, x_val=170):
    cv2.putText(img, key, (x_key, y), FONT, FS, COLOR, THICK, cv2.LINE_AA)
    cv2.putText(img, val, (x_val, y), FONT, FS, COLOR, THICK, cv2.LINE_AA)


def _text_panel(header: str,
                kv_pairs: list[tuple[str, str]],
                lines_single: list[str],
                progress: tuple[int, int] | None = None,
                target_height: int | None = None) -> np.ndarray:
    """
    Auto-width, and height that matches the left image if target_height is given.
    """
    pad_l, pad_r, gap = 10, 14, 18
    base_w = 560  # minimum width so it looks nice

    key_w = max([_text_size(k)[0] for k, _ in kv_pairs] + [0])
    val_w = max([_text_size(v)[0] for _, v in kv_pairs] + [0])
    panel_w = max(base_w, pad_l + key_w + gap + val_w + pad_r)

    y = 52
    needed_h = y
    if progress:
        needed_h += ROW_H
    needed_h += ROW_H * len(kv_pairs)
    if lines_single:
        needed_h += 4 + ROW_H * len(lines_single)
    needed_h += 10

    H = target_height if target_height is not None else max(needed_h, 400)
    img = np.zeros((H, panel_w, 3), np.uint8)

    # header
    cv2.rectangle(img, (0, 0), (panel_w, 30), (25, 25, 25), -1)
    cv2.putText(img, header, (10, 22), cv2.FONT_HERSHEY_SIMPLEX, 0.65, COLOR, 2, cv2.LINE_AA)

    y = 52
    if progress:
        done, total = progress
        frac = 0.0 if total <= 0 else min(1.0, max(0.0, done / float(total)))
        cv2.rectangle(img, (10, y - 10), (panel_w - 10, y - 4), (60, 60, 60), -1)
        bar_w = int((panel_w - 20) * frac)
        cv2.rectangle(img, (10, y - 10), (10 + bar_w, y - 4), COLOR_BAR, -1)
        label = f"{done}/{total} reviewed"
        cv2.putText(img, label, (panel_w - 10 - _text_size(label)[0], y - 12),
                    FONT, 0.45, COLOR, 1, cv2.LINE_AA)
        y += ROW_H

    x_key = pad_l
    x_val = pad_l + key_w + gap
    for k, v in kv_pairs:
        cv2.putText(img, k, (x_key, y), FONT, FS, COLOR, THICK, cv2.LINE_AA)
        cv2.putText(img, v, (x_val, y), FONT, FS, COLOR, THICK, cv2.LINE_AA)
        y += ROW_H

    if lines_single:
        y += 4
    for ln in lines_single:
        cv2.putText(img, ln, (10, y), FONT, FS, COLOR, THICK, cv2.LINE_AA)
        y += ROW_H

    return img


def _pad(img: np.ndarray, h: int, w: int) -> np.ndarray:
    out = np.zeros((h, w, 3), np.uint8)
    out[:img.shape[0], :img.shape[1]] = img
    return out


def _show(left: np.ndarray, right: np.ndarray, win: str = "BBox Review"):
    H = max(left.shape[0], right.shape[0])
    strip = np.hstack([_pad(left, H, left.shape[1]), _pad(right, H, right.shape[1])])
    try:
        cv2.resizeWindow(win, strip.shape[1], strip.shape[0])
    except Exception:
        pass
    cv2.imshow(win, strip)


# Corner/edge indices: 0=NW,1=N,2=NE,3=E,4=SE,5=S,6=SW,7=W
def _handle_points(x: int, y: int, w: int, h: int):
    cx, cy = x + w // 2, y + h // 2
    return [
        (x, y), (cx, y), (x + w, y),
        (x + w, cy),
        (x + w, y + h), (cx, y + h), (x, y + h),
        (x, cy),
    ]


def _point_in_rect(px: int, py: int, x: int, y: int, w: int, h: int) -> bool:
    return (px >= x) and (py >= y) and (px <= x + w) and (py <= y + h)


def _hit_test(px: int, py: int, x: int, y: int, w: int, h: int):
    for idx, (hx, hy) in enumerate(_handle_points(x, y, w, h)):
        if abs(px - hx) <= HANDLE_HIT and abs(py - hy) <= HANDLE_HIT:
            return ("handle", idx)
    if _point_in_rect(px, py, x, y, w, h):
        return ("inside", None)
    return (None, None)


# ---------------------------- Progress persistence ----------------------------
def _load_progress(session_dir: Path) -> dict:
    p = session_dir / PROGRESS_FILE
    if p.exists():
        try:
            return json.loads(p.read_text())
        except Exception:
            pass
    return {"i_frame": 0, "last_idx_name": None, "reviewed": []}


def _save_progress(session_dir: Path, state: dict):
    try:
        tmp = session_dir / (PROGRESS_FILE + ".tmp")
        tmp.write_text(json.dumps(state, indent=2))
        shutil.move(str(tmp), str(session_dir / PROGRESS_FILE))
    except Exception as e:
        log.warning("[progress] failed to save: %s", e)


# ---------------------------- Main ----------------------------
def main():
    project_root = resolve_project_root(None)
    ensure_project_dirs(project_root)

    global log
    log = init_project_logger(project_root / "logs" / "review_bboxes.log",
                              level="INFO", console=True)

    ap = argparse.ArgumentParser("Review & edit bounding boxes in a dataset session")
    ap.add_argument("--session", required=True, help="Dataset session name (folder under datasets/)")
    ap.add_argument("--dataset_root", type=str, default=None,
                    help="Root for datasets; default: <project_root>/datasets")
    ap.add_argument("--filter-class", type=str, default=None,
                    help="Only show objects whose class_name contains this substring")
    ap.add_argument("--use-annotated", action="store_true",
                    help="Display annotated/ image as background instead of images/ raw")
    ap.add_argument("--reset-progress", action="store_true",
                    help="Ignore saved progress and start from the first frame")
    args = ap.parse_args()

    datasets_root = Path(args.dataset_root) if args.dataset_root else (project_root / "datasets")
    session_dir = datasets_root / args.session

    frames = _list_frames(session_dir, use_annotated=args.use_annotated, filter_cls=args.filter_class)
    if not frames:
        sys.exit(f"[!] No annotation frames found in {session_dir}/annotations")

    # progress state
    state = _load_progress(session_dir)
    reviewed: Set[str] = set(state.get("reviewed", []))
    if args.reset_progress:
        i_frame = 0
    else:
        # try restore by idx_name
        start_idx = state.get("last_idx_name")
        if start_idx:
            idx_map = {fr.idx_name: k for k, fr in enumerate(frames)}
            i_frame = idx_map.get(start_idx, int(state.get("i_frame", 0)) % len(frames))
        else:
            i_frame = int(state.get("i_frame", 0)) % len(frames)

    i_obj = 0
    show_help = True

    cv2.namedWindow("BBox Review", cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)
    cv2.resizeWindow("BBox Review", 1280, 720)

    # edit state
    mode = "idle"  # idle | move | resize | drawnew
    resize_handle = None
    drag_origin = None  # (x0,y0) mouse at start
    rect_origin = None  # (x,y,w,h) rect at start
    backup_before_drag = None  # ObjAnno snapshot for cancel

    def _draw_scene(fr: FrameRec) -> Tuple[np.ndarray, np.ndarray, Tuple[int, int]]:
        bgr = cv2.imread(str(fr.image_path), cv2.IMREAD_COLOR)
        if bgr is None:
            bgr = np.zeros((480, 640, 3), np.uint8)
        vis = bgr.copy()
        H, W = vis.shape[:2]

        # draw all boxes
        for j, ob in enumerate(fr.objects):
            x, y, w, h = _norm_to_xywh_px(ob.cx, ob.cy, ob.w, ob.h, W, H)
            selected = (j == i_obj)
            col = (0, 255, 255) if selected else (180, 180, 180)
            th = 3 if selected else 2
            cv2.rectangle(vis, (x, y), (x + w, y + h), col, th, cv2.LINE_AA)
            label = f"{ob.class_name} (#{j})"
            cv2.putText(vis, label, (x, max(16, y - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, col, 2, cv2.LINE_AA)

            if selected:
                for (hx, hy) in _handle_points(x, y, w, h):
                    cv2.rectangle(vis,
                                  (int(hx - HANDLE_SIZE // 2), int(hy - HANDLE_SIZE // 2)),
                                  (int(hx + HANDLE_SIZE // 2), int(hy + HANDLE_SIZE // 2)),
                                  col, -1, cv2.LINE_AA)

        # right panel content
        lines_left = [
            ("Project Root", project_root.name),
            ("Session", session_dir.name),
            ("Frame", f"{i_frame + 1}/{len(frames)}  ({fr.idx_name})"),
            ("Objects", str(len(fr.objects))),
        ]
        tips = [
            "",
            "Mouse: click to select, drag to move,",
            "       drag handles to resize",
            "E: draw-new for selected   |  ESC: cancel",
            "ENTER/Y/S: save+next       |  N: next(skip)",
            "A or LEFT: previous        |  D or RIGHT: next",
            "U: undo selected           |  R: reset frame",
            "Q/q/X/x: quit",
            "",
        ]
        if fr.objects:
            ob = fr.objects[i_obj]
            lines_left += [
                ("Selected Class", f"{ob.class_name} (id={ob.class_id})"),
                ("BBox (norm)", f"cx={ob.cx:.4f}, cy={ob.cy:.4f}, w={ob.w:.4f}, h={ob.h:.4f}"),
                ("Source", f"{ob.bbox_source or '-'}"),
                ("Mode", mode),
            ]

        right = _text_panel(
            "BBox Review / Edit",
            lines_left, tips,
            progress=(len(reviewed), len(frames)),
            target_height=vis.shape[0]  # <-- match left image height
        )
        return vis, right, (W, H)

    # --- mouse callback
    def _on_mouse(event, mx, my, flags, userdata):
        nonlocal mode, resize_handle, drag_origin, rect_origin, backup_before_drag, i_obj

        fr = frames[i_frame]
        if not fr.objects:
            return
        img = cv2.imread(str(fr.image_path), cv2.IMREAD_COLOR)
        H, W = (img.shape[0], img.shape[1]) if img is not None else (480, 640)

        def _get_rect_px(ob: ObjAnno):
            return _norm_to_xywh_px(ob.cx, ob.cy, ob.w, ob.h, W, H)

        if event == cv2.EVENT_LBUTTONDOWN:
            if mode == "drawnew":
                mode = "drawnew"
                drag_origin = (mx, my)
                rect_origin = (mx, my, 0, 0)
                backup_before_drag = None
                return

            # Hit-test (prefer current selection)
            order = list(range(len(fr.objects)))
            if i_obj in order:
                order.remove(i_obj)
                order = [i_obj] + order

            hit = None
            for j in order:
                x, y, w, h = _get_rect_px(fr.objects[j])
                kind, handle_idx = _hit_test(mx, my, x, y, w, h)
                if kind is not None:
                    hit = (j, kind, handle_idx, (x, y, w, h))
                    break

            if hit is not None:
                j, kind, handle_idx, rect = hit
                i_obj = j
                ob = fr.objects[i_obj]
                backup_before_drag = (ob.cx, ob.cy, ob.w, ob.h, ob.bbox_source)
                rect_origin = rect
                drag_origin = (mx, my)
                if kind == "inside":
                    mode = "move";
                    resize_handle = None
                else:
                    mode = "resize";
                    resize_handle = handle_idx

        elif event == cv2.EVENT_MOUSEMOVE:
            if mode in ("move", "resize"):
                ob = fr.objects[i_obj]
                x0, y0, w0, h0 = rect_origin
                dx = mx - drag_origin[0]
                dy = my - drag_origin[1]

                if mode == "move":
                    x = x0 + dx;
                    y = y0 + dy;
                    w = w0;
                    h = h0
                    x, y, w, h = _clamp_xywh(x, y, w, h, W, H)
                else:
                    x, y, w, h = x0, y0, w0, h0
                    if resize_handle in (0, 1, 2):  # top
                        y = y0 + dy;
                        h = (y0 + h0) - y
                    if resize_handle in (4, 5, 6):  # bottom
                        h = h0 + dy
                    if resize_handle in (0, 7, 6):  # left
                        x = x0 + dx;
                        w = (x0 + w0) - x
                    if resize_handle in (2, 3, 4):  # right
                        w = w0 + dx
                    if w < 1: x = x0 + w0 - 1; w = 1
                    if h < 1: y = y0 + h0 - 1; h = 1
                    x, y, w, h = _clamp_xywh(x, y, w, h, W, H)

                cx, cy, ww, hh = _xywh_px_to_norm(x, y, w, h, W, H)
                ob.cx, ob.cy, ob.w, ob.h = cx, cy, ww, hh
                ob.bbox_source = "manual"

            elif mode == "drawnew":
                x0, y0, _, _ = rect_origin
                x1, y1 = mx, my
                x = min(x0, x1);
                y = min(y0, y1)
                w = abs(x1 - x0);
                h = abs(y1 - y0)
                rect_origin = (x, y, w, h)

        elif event == cv2.EVENT_LBUTTONUP:
            if mode in ("move", "resize"):
                mode = "idle";
                resize_handle = None;
                drag_origin = None;
                rect_origin = None;
                backup_before_drag = None
            elif mode == "drawnew":
                x, y, w, h = rect_origin
                if w > 2 and h > 2:
                    ob = fr.objects[i_obj]
                    x, y, w, h = _clamp_xywh(x, y, w, h, W, H)
                    cx, cy, ww, hh = _xywh_px_to_norm(x, y, w, h, W, H)
                    ob.cx, ob.cy, ob.w, ob.h = cx, cy, ww, hh
                    ob.bbox_source = "manual"
                mode = "idle";
                drag_origin = None;
                rect_origin = None

        elif event == cv2.EVENT_RBUTTONDOWN:
            _cancel_current_edit(fr)

    def _cancel_current_edit(fr: FrameRec):
        nonlocal mode, resize_handle, drag_origin, rect_origin, backup_before_drag
        if mode in ("move", "resize") and backup_before_drag is not None:
            ob = fr.objects[i_obj]
            ob.cx, ob.cy, ob.w, ob.h, ob.bbox_source = backup_before_drag
        mode = "idle";
        resize_handle = None;
        drag_origin = None;
        rect_origin = None;
        backup_before_drag = None

    cv2.setMouseCallback("BBox Review", _on_mouse)

    # -------------------- main loop --------------------
    while True:
        fr = frames[i_frame]
        left, right, (W, H) = _draw_scene(fr)
        _show(left, right, "BBox Review")
        k = cv2.waitKey(15) & 0xFF

        # Quit always works
        if k in (ord('Q'), ord('q'), ord('X'), ord('x')):
            # persist last position even if not saving this frame
            state["i_frame"] = i_frame
            state["last_idx_name"] = fr.idx_name
            state["reviewed"] = sorted(list(reviewed))
            _save_progress(session_dir, state)
            break

        # Cancel edit
        if k == 27:  # ESC
            _cancel_current_edit(fr)
            continue

        if k in (ord('h'), ord('H')):
            show_help = not show_help
        elif k in (ord('a'), 81):  # 'a' or LEFT
            i_frame = (i_frame - 1) % len(frames);
            i_obj = 0
        elif k in (ord('d'), 83):  # 'd' or RIGHT
            i_frame = (i_frame + 1) % len(frames);
            i_obj = 0
        elif k in (ord('u'), ord('U')):
            if fr.objects: fr.objects[i_obj].undo()
        elif k in (ord('r'), ord('R')):
            for ob in fr.objects: ob.undo()
        elif k in (ord('n'), ord('N')):  # next without saving
            i_frame = (i_frame + 1) % len(frames);
            i_obj = 0
            # update "last visited" so resume lands here next time
            state["i_frame"] = i_frame
            state["last_idx_name"] = frames[i_frame].idx_name
            _save_progress(session_dir, state)
        elif k in (ord('e'), ord('E')):  # draw-new for selected
            if fr.objects:
                mode = "drawnew";
                resize_handle = None;
                drag_origin = None;
                rect_origin = (0, 0, 0, 0)
        elif k in (13, ord('y'), ord('Y'), ord('s'), ord('S')):  # SAVE + NEXT
            try:
                rec = json.loads(fr.json_path.read_text())
                objs = rec.get("objects", [])
                for ob in fr.objects:
                    if 0 <= ob.index < len(objs):
                        objs[ob.index]["2D_center"] = [float(ob.cx), float(ob.cy)]
                        objs[ob.index]["width"] = float(ob.w)
                        objs[ob.index]["height"] = float(ob.h)
                        objs[ob.index]["bbox_source"] = ob.bbox_source or "manual"
                rec["objects"] = objs
                _atomic_write_json(fr.json_path, rec)
                log.info("[saved] %s", fr.json_path.name)
                reviewed.add(fr.idx_name)
            except Exception as e:
                log.error("[!] Failed to save %s: %s", fr.json_path, e)
            # advance + persist resume point
            i_frame = (i_frame + 1) % len(frames);
            i_obj = 0
            state["i_frame"] = i_frame
            state["last_idx_name"] = frames[i_frame].idx_name
            state["reviewed"] = sorted(list(reviewed))
            _save_progress(session_dir, state)

    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
